######################################################################
# Automatically generated by qmake (2.00a) Thu Oct 4 18:48:57 2007
######################################################################

TEMPLATE = app
TARGET +=
DEPENDPATH += .
INCLUDEPATH += .
CONFIG -= qt
CONFIG += release opengl
LIBS += -lavformat -lavcodec -lavutil -lswscale -lz
LIBS += -lglut
#QMAKE_CXXFLAGS_RELEASE += -pedantic -ansi

# Input
SOURCES += VideoStream.cpp main.cpp
HEADERS += VideoStream.h
